export {default as Landing} from './Landing'
export {default as About} from './About'
export { default as LoginPage } from './LoginPage'
export { default as Register } from './Register'
export { default as HomeLayout } from './HomeLayout'
export { default as ErrorPage } from './ErrorPage'
export { default as SingleMovie } from './SingleMovie'
export { default as Ticket } from './Ticket'